// ============================================================
// SMARTLING INTEGRATIONS HUB — DATA FILE
// ============================================================
// All site content lives here. Edit these arrays and objects
// to update the site. No layout or logic files need changing
// for routine content updates.
// ============================================================

// ─────────────────────────────────────────────────────────────
// SECTION 1: WHAT'S NEW — Release Updates
// UPDATE: Add new releases here, newest first.
// ─────────────────────────────────────────────────────────────
let RELEASES = []

// ─────────────────────────────────────────────────────────────
// SECTION 2: WORK IN PROGRESS
// UPDATE: Update connector stages and ETAs here.
// Stages: Discovery | Design | Build | QA | Launching
// ─────────────────────────────────────────────────────────────
let WIP_ITEMS = []

// ─────────────────────────────────────────────────────────────
// SECTION 3: ROADMAP
// UPDATE: Move items between horizons as priorities shift.
// Horizons: now (active this quarter), next (next quarter),
//           later (backlog / under evaluation)
// ─────────────────────────────────────────────────────────────
let ROADMAP = { now: [], next: [], later: [] };

// ─────────────────────────────────────────────────────────────
// SECTION 4: CONNECTOR CATALOG
// UPDATE: Add new connectors here. Keep sorted by category.
// Status values: stable | beta | deprecated | coming-soon
// ─────────────────────────────────────────────────────────────
let CONNECTORS = []

// ─────────────────────────────────────────────────────────────
// SECTION 5: CONNECTOR HEALTH & STATUS
// UPDATE: Update status and lastVerified dates regularly.
// Status values: operational | degraded | maintenance | deprecated
// ─────────────────────────────────────────────────────────────
let HEALTH_STATUSES = {};

// ─────────────────────────────────────────────────────────────
// SECTION 6: KNOWN ISSUES & ACTIVE INCIDENTS
// UPDATE: Add new issues here. Move to status: 'resolved' when fixed.
// Severity: critical | high | medium | low
// Status: investigating | in-progress | resolved
// ─────────────────────────────────────────────────────────────
let KNOWN_ISSUES = []

// ─────────────────────────────────────────────────────────────
// SECTION 8: RELEASE & TRAINING CALENDAR
// UPDATE: Add upcoming releases, training sessions, and events here.
// Types: release | training | webinar | office-hours | milestone
// ─────────────────────────────────────────────────────────────
let CALENDAR_EVENTS = []

// ─────────────────────────────────────────────────────────────
// SECTION 9: TRAINING RESOURCES & ENABLEMENT HUB
// UPDATE: Add new resources here.
// Audiences: sales | cs | se | all
// Types: recording | deck | guide | battlecard | matrix | walkthrough | quick-ref
// ─────────────────────────────────────────────────────────────
let TRAINING_RESOURCES = []

// ─────────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────
// SECTION 10: CONNECTOR COMPARISON MATRIX
// Populated live from the Comparison_matrix Google Sheet.
// Values come from the sheet: true/yes/✓, false/no/-, partial/~, planned
// ─────────────────────────────────────────────────────────────
let COMPARISON_MATRIX_DATA = [];

// ─────────────────────────────────────────────────────────────
// SECTION 11: RESEARCH
// Populated live from the Research Google Sheet tab.
// Fields: id, title, type (doc|slides|pdf), date, status
//         (draft|published|archived), author, summary, link, tags
// ─────────────────────────────────────────────────────────────
let RESEARCH_ITEMS = [];


// UPDATE: Historical data seeded from Google Sheet. Do not edit manually.
// To add new historical entries, use the form above instead.
const SEED_REQUESTS = [
  {"id": 1, "date": "2023-02-24", "integration": "Intercom", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Mintel", "contact": "", "sfLink": "", "urgency": "I would like to have this integration to create new ecosystem market opportunities", "funding": "No", "competitors": "Lokalise", "workaround": "D&D", "context": "intercom comes up fairly regularly, lokalise has a connector so we lose business to them for that reason.. and Intercom is a Smartling customer - not sure how big the opportunity would be but might be worth exploring at some point, not least as part of the opportunity is tickets, chat and therefore an MT play (like the Monese ZD tickets + autoselect solution)", "submittedAt": "2023-02-24T03:19:02Z", "source": "historical"},
  {"id": 2, "date": "2023-02-24", "integration": "Optimizely CMP", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Optimizely", "contact": "Simon Chapman", "sfLink": "", "urgency": "A new interested ISV Technology Partner integration request", "funding": "", "competitors": "No other TMS has a connector, so greenfield opp", "workaround": "", "context": "Optimizely has 400 CMP customers, including brands like Shell, BMC, Grant Thornton. CMP MD has requested a connector be built to Smartling asap, so as an interim solution, Simon's team is building a connector", "submittedAt": "2023-02-24T09:51:25Z", "source": "historical"},
  {"id": 3, "date": "2023-01-27", "integration": "StoryBlok", "requestorName": "Mike Hurst", "requestorEmail": "mhurst@smartling.com", "company": "StoryBlok", "contact": "Simon Turner", "sfLink": "", "urgency": "A new interested ISV Technology Partner integration request", "funding": "", "competitors": "Lokalise, Crowdin, Localazy, Weglot", "workaround": "Storyblok has manual import/export method based on a integrator blog.", "context": "Met with partnership contact to discuss the business case. Very small US Market opportunity based on account mapping. EU market mostly, but they are focused on growing in the US. We have provided sandbox access to determine if this could be an ecosystem-developed integration. Known shared client is H&M", "submittedAt": "2023-02-24T10:17:15Z", "source": "historical"},
  {"id": 4, "date": "2023-01-26", "integration": "Webflow", "requestorName": "Mike Hurst", "requestorEmail": "mhurst@smartling.com", "company": "Webflow", "contact": "Pegi Karger", "sfLink": "", "urgency": "A new interested ISV Technology Partner integration request", "funding": "", "competitors": "Conveythis, Crowdin, Transifex, Text United, Lokalize.js, Weglot", "workaround": "Smartling GDN", "context": "i10N support is the #1 feature request. Smartling is the #1 Enterprise Translation Platform vendor target. 25% of their business is enterprise skus. No enterprise TMS partner currently.", "submittedAt": "2023-02-24T10:59:11Z", "source": "historical"},
  {"id": 5, "date": "2023-01-05", "integration": "Stensul", "requestorName": "Mike Hurst", "requestorEmail": "mhurst@smartling.com", "company": "Stensul", "contact": "Blaine Stillerman", "sfLink": "", "urgency": "A new interested ISV Technology Partner integration request", "funding": "", "competitors": "None, they are engaging with translation vendor for a Q3 launch", "workaround": "", "context": "Conducting a business case, sandbox access provided to Blaine. Met with CRO/CEO. This would be a Stensul-built integration. Disney+ is the known shared client.", "submittedAt": "2023-02-24T11:04:27Z", "source": "historical"},
  {"id": 6, "date": "2023-02-17", "integration": "Hygraph", "requestorName": "Mike Hurst from Dylan Rooney", "requestorEmail": "mhurst@smartling.com", "company": "Epic Games", "contact": "Arthur Flew", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "", "competitors": "Lokalise", "workaround": "", "context": "Hygraph's preference is to build the integration. Sandbox and API access has been provided.", "submittedAt": "2023-02-24T11:12:02Z", "source": "historical"},
  {"id": 7, "date": "2023-02-24", "integration": "Make Swift", "requestorName": "Michael Stevens", "requestorEmail": "mhurst@smartling.com", "company": "Make Shift", "contact": "Miguel Oller CTO, Smartling Client BigCommerce", "sfLink": "", "urgency": "A new interested ISV Technology Partner integration request", "funding": "", "competitors": "No existing competitors", "workaround": "", "context": "Make Swift https://www.makeswift.com/ they are working with BigCommerce who is using Contentful and will use the connector but these guys want to integrate with us and be a partner", "submittedAt": "2023-02-27T20:01:21Z", "source": "historical"},
  {"id": 8, "date": "2023-02-22", "integration": "Pendo", "requestorName": "Jose Vasquez", "requestorEmail": "jvasquez@smartling.com", "company": "Vimeo", "contact": "Liliana Pardo-Becerra", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Yes", "competitors": "Not sure", "workaround": "No", "context": "", "submittedAt": "2023-03-03T08:54:21Z", "source": "historical"},
  {"id": 9, "date": "2023-03-20", "integration": "CleverTap", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "StockX", "contact": "Isabella Teodoro - Senior Localization Project Manager", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0012A00001rJt5GQAS/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Possibly", "competitors": "N/A", "workaround": "No, this is a new system for StockX", "context": "", "submittedAt": "2023-04-03T12:14:56Z", "source": "historical"},
  {"id": 10, "date": "2023-04-18", "integration": "Salsify", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "VF Corp and Fox Racing", "contact": "Director of Digital", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "TDC", "workaround": "Smartling API", "context": "Account value question - Fox Racing will use our API, however this has now come up on other prospect calls such as VF Corp.", "submittedAt": "2023-04-18T11:13:57Z", "source": "historical"},
  {"id": 11, "date": "2023-04-27", "integration": "Sendgrid and Blueshift", "requestorName": "Jennifer Levee", "requestorEmail": "jlevee@smartling.com", "company": "Carrot Fertility", "contact": "Jesse Schneider", "sfLink": "Carrot Fertility", "urgency": "No SLS opportunity upside, and provides Smartling customer retention and automation value", "funding": "It was not asked", "competitors": "Crowdin", "workaround": "Github", "context": "", "submittedAt": "2023-04-27T11:34:05Z", "source": "historical"},
  {"id": 12, "date": "2023-05-02", "integration": "Intercom", "requestorName": "Jenn Levee", "requestorEmail": "jlevee@smartling.com", "company": "Prospect: Vidmob & Convertkit", "contact": "n/a", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j000014d9E0AAI/view", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "No", "competitors": "Crowdin", "workaround": "Smartling GDN", "context": "Intercom has come up for two creative marketing software platforms - both opportunities I'm working on", "submittedAt": "2023-05-02T13:57:00Z", "source": "historical"},
  {"id": 13, "date": "2023-08-04", "integration": "Webflow", "requestorName": "Jenn Levee", "requestorEmail": "jlevee@smartling.com", "company": "Carrot Fertility", "contact": "Erik Eaton", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j000014dPukAAE/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "Weglot", "workaround": "Smartling GDN", "context": "Carrot marketing decided on Weglot for a quick solution when we originally discussed the opportunity. They are back asking to evaluate GDN as they private beta the new Weglot solution rolling out in Q4.", "submittedAt": "2023-08-04T11:10:49Z", "source": "historical"},
  {"id": 14, "date": "2023-08-04", "integration": "Webflow", "requestorName": "Jenn Levee", "requestorEmail": "jlevee@smartling.com", "company": "Avetta", "contact": "Yulia Solokova", "sfLink": "", "urgency": "No SLS opportunity upside, and provides Smartling customer retention and automation value", "funding": "No, You would prefer that we do not ask (Strategic Customer)", "competitors": "Weglot, new Weglot solution should integrate to all/most Smartling competitors including XTM", "workaround": "", "context": "Avetta started with the GDN and could never get the internal resources to get things off the ground. They then went to Drupal, which they are now migrating off to Webflow. If the new Weglot solution connects to Smartling competitors, we will see more competition.", "submittedAt": "2023-08-04T11:14:44Z", "source": "historical"},
  {"id": 15, "date": "2023-08-09", "integration": "Paligo", "requestorName": "Steven Zapata", "requestorEmail": "szapata@smartling.com", "company": "Packsize", "contact": "michael.white@packsize.com", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Phrase", "workaround": "", "context": "I don't think they would be willing to pay for it because it doesn't seem like it hosts a lot of content that will need to be translated.", "submittedAt": "2023-08-09T11:19:44Z", "source": "historical"},
  {"id": 16, "date": "2023-08-21", "integration": "Iterable", "requestorName": "Emily Sisk", "requestorEmail": "esisk@smartling.com", "company": "Hinge Health", "contact": "Kevin Dukovic", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0012A00002XpQ9OQAV/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked, You would prefer that we do not ask (Strategic Customer)", "competitors": "Lokalize and Crowdin", "workaround": "Suggested API but customer does not have the bandwidth", "context": "Customer is actively demoing other solutions because they have out of the box connectors.", "submittedAt": "2023-08-21T11:49:54Z", "source": "historical"},
  {"id": 17, "date": "2023-08-30", "integration": "Ticketing support for Salesforce Service Cloud", "requestorName": "Fouz", "requestorEmail": "mmahfouz@smartling.com", "company": "CPM International", "contact": "Noe Gest", "sfLink": "N/A", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "No", "competitors": "Lingotek", "workaround": "Smartling API", "context": "", "submittedAt": "2023-08-30T07:21:15Z", "source": "historical"},
  {"id": 18, "date": "2023-09-25", "integration": "Iterable", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Brightline", "contact": "Katie Fisher", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j000019xestAAA/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "Yes", "workaround": "Smartling API", "context": "", "submittedAt": "2023-09-25T14:26:19Z", "source": "historical"},
  {"id": 19, "date": "2023-09-28", "integration": "SAP Commerce Cloud", "requestorName": "Michael Keller", "requestorEmail": "mkeller@smartling.com", "company": "SAP (site: trends.builtwith.com)", "contact": "", "sfLink": "", "urgency": "I would like to have this integration to create new ecosystem market opportunities", "funding": "No", "competitors": "Lionbridge, Weglot, Transperfect, RWS, Acolad, Across", "workaround": "", "context": "SAP Hybris is not supported by SAP anymore. SAP is our client.", "submittedAt": "2023-09-28T08:14:15Z", "source": "historical"},
  {"id": 20, "date": "2023-10-02", "integration": "Notion", "requestorName": "David McNeil", "requestorEmail": "dmcneil@smartling.com", "company": "Lucca", "contact": "Mathieu Cresp", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j000014dge9AAA/view", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "It was not asked", "competitors": "Crowdin", "workaround": "", "context": "", "submittedAt": "2023-10-05T03:36:46Z", "source": "historical"},
  {"id": 21, "date": "2023-10-04", "integration": "Drift Chat (live and pre-scripted)", "requestorName": "David McNeil", "requestorEmail": "dmcneil@smartling.com", "company": "Henkel", "contact": "Olawale Ajayi", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j00001BY1JIAA1/view", "urgency": "Nice to Have requirement for an RFP/RFI", "funding": "It was not asked", "competitors": "Unsure", "workaround": "", "context": "", "submittedAt": "2023-10-05T03:52:11Z", "source": "historical"},
  {"id": 22, "date": "2023-10-09", "integration": "Intellum", "requestorName": "Gary Biggs", "requestorEmail": "gbiggs@smartling.com", "company": "Spotify", "contact": "Donna Kelly", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j000014cqbeAAA/view", "urgency": "No SLS opportunity upside, and provides Smartling customer retention and automation value", "funding": "Yes", "competitors": "Not sure", "workaround": "", "context": "$45,000 was the agreed fee previously. I'm submitting this to put more visibility onto it and follow the correct Smartling procedure.", "submittedAt": "2023-10-09T05:10:14Z", "source": "historical"},
  {"id": 23, "date": "2023-08-16", "integration": "ServiceNow", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Zoom", "contact": "Ciara Harris & Summer Zhao - Global Loc Manager", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "Yes", "competitors": "XTM claims they do but they have not tried it yet", "workaround": "We mentioned that we have customers integrated via the API already", "context": "", "submittedAt": "2023-10-12T08:06:12Z", "source": "historical"},
  {"id": 24, "date": "2023-10-14", "integration": "Coremedia", "requestorName": "David McNeil", "requestorEmail": "dmcneil@smartling.com", "company": "Turck", "contact": "", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j000019vxptAAA/view", "urgency": "I would like to have this integration to create new ecosystem market opportunities", "funding": "It was not asked", "competitors": "Transperfect, Transline", "workaround": "", "context": "", "submittedAt": "2023-10-17T08:28:58Z", "source": "historical"},
  {"id": 25, "date": "2023-10-18", "integration": "Open EdX", "requestorName": "Jennifer Levee", "requestorEmail": "jlevee@smartling.com", "company": "PearsonVUE", "contact": "Bryan Ochs", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j00001BawaSAAR/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "Unknown", "workaround": "Smartling API, Repo Connector / CLI", "context": "Pearson Vue is the largest creator of computer-based testing using Open EdX. Files types are EPUB which we don't support.", "submittedAt": "2023-10-18T10:09:27Z", "source": "historical"},
  {"id": 26, "date": "2023-10-31", "integration": "Paligo", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Health Catalyst and Proscia", "contact": "Bonnie Swanson", "sfLink": "", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "It was not asked", "competitors": "I am not sure", "workaround": "", "context": "Early stages with these opps but I am noticing Paligo coming up more and more", "submittedAt": "2023-11-01T07:40:51Z", "source": "historical"},
  {"id": 27, "date": "2023-11-02", "integration": "SF Service Cloud - case management support for tickets", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Accenture (partnership play)", "contact": "Rasmus Josefsen - Experience Transformation Manager", "sfLink": "", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "It was not asked", "competitors": "Unsure", "workaround": "", "context": "", "submittedAt": "2023-11-02T08:49:20Z", "source": "historical"},
  {"id": 28, "date": "2023-11-30", "integration": "InRiver PIM", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Fisher & Paykel / Reynaers", "contact": "Sue Lewis", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Unsure", "workaround": "", "context": "To date we said we can support via API but this has come up in other opps too", "submittedAt": "2023-11-30T13:16:34Z", "source": "historical"},
  {"id": 29, "date": "2023-12-01", "integration": "Shopify", "requestorName": "Fouz", "requestorEmail": "mmahfouz@smartling.com", "company": "Therabody", "contact": "Dominic Yeo - Senior Program Manager, Localization", "sfLink": "N/A - Current customer", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Yes, Possibly", "competitors": "GlobalLink, CrowdIn", "workaround": "Smartling GDN", "context": "Therabody is migrating from SFCC to Shopify, target date of July 2024", "submittedAt": "2023-12-01T13:11:47Z", "source": "historical"},
  {"id": 30, "date": "2023-12-18", "integration": "S3 Bucket", "requestorName": "David McNeil", "requestorEmail": "dmcneil@smartling.com", "company": "eToro", "contact": "nurithte@etoro.com", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/0063j000014cdu0AAA/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Possibly", "competitors": "POeditor", "workaround": "Suggested API but was not seen as a viable option as they are currently using POeditor and don't want to do the development work", "context": "", "submittedAt": "2023-12-18T08:06:09Z", "source": "historical"},
  {"id": 31, "date": "2024-01-16", "integration": "Bynder", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Align Technology", "contact": "Marlena - Procurement", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK000002UrXBYA0/view", "urgency": "Must Have requirement for an RFP/RFI", "funding": "It was not asked", "competitors": "IDK", "workaround": "Smartling API", "context": "", "submittedAt": "2024-01-22T07:28:41Z", "source": "historical"},
  {"id": 32, "date": "2024-02-14", "integration": "Sitecore XM Cloud", "requestorName": "James Ganswindt", "requestorEmail": "jganswindt@smartling.com", "company": "Blue Yonder", "contact": "Jeff Edgett", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "", "competitors": "Churned from TPT, no other competitors mentioned", "workaround": "Smartling GDN", "context": "New client on Sitecore XM Cloud, churned from TPT because they couldn't support. Prospect liked the GDN approach.", "submittedAt": "2024-02-14T12:57:41Z", "source": "historical"},
  {"id": 33, "date": "2024-02-21", "integration": "Webflow", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Klaviyo", "contact": "", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/001F000001tff7eIAA/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No, You would prefer that we do not ask (Strategic Customer)", "competitors": "Yes", "workaround": "No", "context": "Likely a requirement for mid/late Q2", "submittedAt": "2024-02-21T10:47:58Z", "source": "historical"},
  {"id": 34, "date": "2024-02-28", "integration": "Microsoft SharePoint", "requestorName": "Garrett Schneider", "requestorEmail": "gschneider@smartling.com", "company": "Itron", "contact": "", "sfLink": "", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "No, It was not asked", "competitors": "N/A", "workaround": "", "context": "The question came on a prospect call - not a hard requirement but a nice to have. I have been asked about a SharePoint integration a few times in the past 2 months.", "submittedAt": "2024-02-28T11:05:44Z", "source": "historical"},
  {"id": 35, "date": "2024-03-13", "integration": "Webflow", "requestorName": "Adam O'Reilly", "requestorEmail": "aoreilly@smartling.com", "company": "Confluent", "contact": "Ronja Antesburger", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Yes", "competitors": "No", "workaround": "Smartling GDN, Smartling API", "context": "", "submittedAt": "2024-03-13T09:04:50Z", "source": "historical"},
  {"id": 36, "date": "2024-03-13", "integration": "Webflow", "requestorName": "James Ganswindt", "requestorEmail": "jganswindt@smartling.com", "company": "Confluent", "contact": "Ronja Antesberger", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "No", "workaround": "Smartling GDN", "context": "The CSM let the client know they could use GDN instead of Webflow for the time being.", "submittedAt": "2024-03-13T09:49:51Z", "source": "historical"},
  {"id": 37, "date": "2024-03-20", "integration": "XLoc Integration", "requestorName": "Lynn Nguyen & Mallory Russell", "requestorEmail": "lnguyen@smartling.com", "company": "Activision", "contact": "Barry Kehoe", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "Yes", "competitors": "MemoQ", "workaround": "Currently Activision has an XLoc integration with MemoQ", "context": "Activision would like to centralize all of their localization into a single platform. They currently use Smartling for Marketing and MemoQ for in-game content. They use XLoc and currently integrate with MemoQ.", "submittedAt": "2024-03-20T10:25:39Z", "source": "historical"},
  {"id": 38, "date": "2024-03-22", "integration": "Shopify", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "New Era", "contact": "Head of Ecommerce", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "No", "competitors": "Yes", "workaround": "Only option is D&D which they're not prepared to do", "context": "", "submittedAt": "2024-03-22T03:24:32Z", "source": "historical"},
  {"id": 39, "date": "2024-05-08", "integration": "Sitecore XM", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "ASML", "contact": "", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "Yes", "competitors": "Yes", "workaround": "Pitched GDN, rejected and qualified us out due to no pre-built connector", "context": "", "submittedAt": "2024-05-31T02:45:54Z", "source": "historical"},
  {"id": 40, "date": "2024-05-31", "integration": "Pardot (Salesforce Marketing Cloud Account Engagement)", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Legal & General", "contact": "", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "Translation integrations available via Workato", "workaround": "Smartling GDN", "context": "Mid-stage opp requesting it", "submittedAt": "2024-05-31T02:50:24Z", "source": "historical"},
  {"id": 41, "date": "2024-05-31", "integration": "Seismic", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Legal & General", "contact": "", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "Yes", "workaround": "", "context": "", "submittedAt": "2024-05-31T02:51:13Z", "source": "historical"},
  {"id": 42, "date": "2024-05-31", "integration": "Pardot", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Epidemic Sounds", "contact": "", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "No", "competitors": "Yes via Workato", "workaround": "Smartling GDN", "context": "", "submittedAt": "2024-05-31T02:51:57Z", "source": "historical"},
  {"id": 43, "date": "2024-06-26", "integration": "Salesforce Service Cloud", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Circle", "contact": "Hue-Kan Tran and Jim Rubino", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j000034sH6DAAU/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "You would prefer that we do not ask (Strategic Customer)", "competitors": "Language i/o, Intento", "workaround": "Same use case as ZD tickets", "context": "They seem to be against building a custom integration so it's possible they may turn to Language i/O to lower the overall TCO", "submittedAt": "2024-06-26T07:29:59Z", "source": "historical"},
  {"id": 44, "date": "2024-07-08", "integration": "Intercom", "requestorName": "Kian Graham", "requestorEmail": "kgraham@smartling.com", "company": "Siteminder", "contact": "felipe.costa@siteminder.com", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/001F000001Oas2BIAR/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Yes", "competitors": "They mentioned calls with competitors who have an integration", "workaround": "Siteminder have been using our Google Drive connector as a workaround", "context": "They said no to funding the development, too expensive. Long time customer happy with platform but want us to have an Intercom integration.", "submittedAt": "2024-07-08T08:11:53Z", "source": "historical"},
  {"id": 45, "date": "2024-07-08", "integration": "Mailgun", "requestorName": "Philippe St. Marseille", "requestorEmail": "pmarseille@smartling.com", "company": "Brightline", "contact": "Laura Wyatt", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j000034uJbeAAE/view", "urgency": "No SLS opportunity upside, and provides Smartling customer retention and automation value", "funding": "", "competitors": "Yes - Crowdin", "workaround": "Manual drag & drop", "context": "This connector would be helpful and reduce their manual work.", "submittedAt": "2024-07-08T08:19:13Z", "source": "historical"},
  {"id": 46, "date": "2024-07-22", "integration": "Intercom", "requestorName": "Kian Graham", "requestorEmail": "kgraham@smartling.com", "company": "Opensea", "contact": "Celine Lombardi - Product Manager", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j000031wCGwAAM/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Yes", "competitors": "Not to my knowledge yet", "workaround": "", "context": "", "submittedAt": "2024-07-22T06:57:01Z", "source": "historical"},
  {"id": 47, "date": "2024-07-24", "integration": "Salsify", "requestorName": "Kian Graham", "requestorEmail": "kgraham@smartling.com", "company": "Solo Stove", "contact": "Jordan Cohen SVP Digital", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j000031w91cAAA/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "No but Smartcat has one", "workaround": "No", "context": "", "submittedAt": "2024-07-24T09:17:31Z", "source": "historical"},
  {"id": 48, "date": "2024-08-06", "integration": "Articulate", "requestorName": "Jose Vasquez", "requestorEmail": "jvasquez@smartling.com", "company": "Volvo, Lenovo and BeyondTrust", "contact": "L&D teams", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Not sure", "workaround": "Drag and drop", "context": "", "submittedAt": "2024-08-06T09:23:03Z", "source": "historical"},
  {"id": 49, "date": "2024-08-22", "integration": "Webflow", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "CAS", "contact": "Drew Norman", "sfLink": "", "urgency": "I would like to have this integration to create new ecosystem market opportunities", "funding": "No", "competitors": "Phrase", "workaround": "", "context": "", "submittedAt": "2024-08-22T10:09:07Z", "source": "historical"},
  {"id": 50, "date": "2024-08-28", "integration": "Sitecore XM Cloud", "requestorName": "Philippe St. Marseille", "requestorEmail": "pmarseille@smartling.com", "company": "NTT Data", "contact": "Cindy Redman", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Unknown", "workaround": "", "context": "NTT Data is an expansion opportunity. In 2025, the company is looking to consolidate their TMS. They said they are likely switching to Sitecore XM Cloud in 2025, and that having this connector could 'make or break our decision to use Smartling.'", "submittedAt": "2024-08-28T11:16:09Z", "source": "historical"},
  {"id": 51, "date": "2024-10-04", "integration": "Zendesk Chat", "requestorName": "Fouz", "requestorEmail": "mmahfouz@smartling.com", "company": "Atera", "contact": "Alexandra Potchter - CS Ops", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000B8HVBYA3/view", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "No, It was not asked", "competitors": "Language.io", "workaround": "Smartling API", "context": "Seems like the next step in our Zendesk connector - MT usage for this opp is unknown", "submittedAt": "2024-10-04T08:19:13Z", "source": "historical"},
  {"id": 52, "date": "2024-10-09", "integration": "Salesforce Service Cloud", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Edrington", "contact": "Morven Clements", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j00002bAByfAAG/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Yes", "workaround": "Smartling API", "context": "Key use case for them moving forward", "submittedAt": "2024-10-09T04:25:30Z", "source": "historical"},
  {"id": 53, "date": "2024-10-09", "integration": "Salsify", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Edrington", "contact": "Morven Clements", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j00002bAByfAAG/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Yes", "workaround": "Smartling API", "context": "A key use case moving forward", "submittedAt": "2024-10-09T04:26:30Z", "source": "historical"},
  {"id": 54, "date": "2024-11-04", "integration": "Salesforce Service Cloud (email-to-case, web-to-case, LiveChat)", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Trustpilot", "contact": "Multiple", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000CFxdvYAD/view", "urgency": "Must Have requirement for an RFP/RFI", "funding": "No", "competitors": "Unsure", "workaround": "", "context": "", "submittedAt": "2024-11-04T09:58:02Z", "source": "historical"},
  {"id": 55, "date": "2024-11-06", "integration": "Wistia", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Trustpilot", "contact": "Multiple", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000CFxdvYAD/view", "urgency": "Must Have requirement for an RFP/RFI", "funding": "It was not asked", "competitors": "Unknown", "workaround": "", "context": "", "submittedAt": "2024-11-06T01:04:54Z", "source": "historical"},
  {"id": 56, "date": "2024-12-09", "integration": "Webflow", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Darktrace", "contact": "Rachel Nislick, VP Revenue Marketing", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000DFGJVYA5/view", "urgency": "Must Have requirement for an RFP/RFI", "funding": "No", "competitors": "Lokalise", "workaround": "", "context": "Previously worked with us at Mimecast", "submittedAt": "2024-12-11T08:51:00Z", "source": "historical"},
  {"id": 57, "date": "2024-12-11", "integration": "Gainsight Customer Community", "requestorName": "David McNeil", "requestorEmail": "dmcneil@smartling.com", "company": "Docusign", "contact": "", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/001F000000gUiOtIAK/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Not that I am aware of", "workaround": "", "context": "This is for both static e.g. landing pages and UGC e.g. forum posts. For Docusign both would be in scope with a focus on MT for UGC.", "submittedAt": "2024-12-11T08:53:20Z", "source": "historical"},
  {"id": 58, "date": "2025-02-13", "integration": "Salsify", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Renishaw", "contact": "Megan Hilleard, Group Localization Manager", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "It was not asked", "competitors": "SmartCat, MotionPoint, TransPerfect/GlobalLink", "workaround": "Smartling API", "context": "Also require integrations with ContentStack, Marketo and Adobe Illustrator, so a good fit apart from Salsify", "submittedAt": "2025-02-13T13:55:26Z", "source": "historical"},
  {"id": 59, "date": "2025-02-13", "integration": "Salsify", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Edrington", "contact": "Morven Clements, Digital Product Owner", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j00002bAByfAAG/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "SmartCat, MotionPoint, GlobalLink / TransPerfect", "workaround": "Call to discuss options scheduled Feb 24th", "context": "Integrated with Drupal - not much traction there yet. Exploring the HubSpot connector. Seems most of their content is in Salsify - need to establish how it's being translated today.", "submittedAt": "2025-02-13T13:58:25Z", "source": "historical"},
  {"id": 60, "date": "2025-02-14", "integration": "DatoCMS", "requestorName": "Michael Keller", "requestorEmail": "mkeller@smartling.com", "company": "Polestar", "contact": "", "sfLink": "", "urgency": "Nice to Have requirement for an RFP/RFI", "funding": "Possibly", "competitors": "Crowdin, XTM", "workaround": "Smartling GDN, Smartling API", "context": "", "submittedAt": "2025-02-14T06:27:42Z", "source": "historical"},
  {"id": 61, "date": "2025-02-18", "integration": "Zoom/Teams/Google Meet", "requestorName": "David McNeil", "requestorEmail": "dmcneil@smartling.com", "company": "MongoDB", "contact": "fabian.valle-simmons@mongodb.com", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Unknown", "workaround": "Smartling API", "context": "Customer wants real-time meeting transcript translation. Teams has slightly better support for captions+translation but requires a custom app. If Smartling has integrations for Zoom or Teams, this makes life a lot easier. Also mentioned recall.ai as an option.", "submittedAt": "2025-02-18T06:53:35Z", "source": "historical"},
  {"id": 62, "date": "2025-03-14", "integration": "InRiver", "requestorName": "Mihaly Medzihradszky", "requestorEmail": "mmedzihradszky@smartling.com", "company": "Alfa Laval", "contact": "Christian Bonnichsen", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000G5mUDYAZ/view", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "No", "competitors": "Transperfect, Language Wire, Lionbridge, Semantix", "workaround": "No implementation yet.", "context": "InRiver integration keeps popping up with manufacturing companies in Europe", "submittedAt": "2025-03-14T01:06:09Z", "source": "historical"},
  {"id": 63, "date": "2025-03-28", "integration": "Salesforce Service Cloud", "requestorName": "Kian Graham", "requestorEmail": "kgraham@smartling.com", "company": "Affirm", "contact": "Multiple contacts interested", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/001F000001N2AUzIAN/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "You would prefer that we do not ask (Strategic Customer)", "competitors": "Smartcat", "workaround": "", "context": "MT Upside - Affirm are expanding into Europe", "submittedAt": "2025-03-28T08:36:57Z", "source": "historical"},
  {"id": 64, "date": "2025-03-28", "integration": "Sitecore XM Cloud", "requestorName": "Adam Bye", "requestorEmail": "abye@smartling.com", "company": "Fortescue", "contact": "", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "No", "competitors": "As known", "workaround": "", "context": "", "submittedAt": "2025-03-28T10:45:12Z", "source": "historical"},
  {"id": 65, "date": "2025-04-02", "integration": "Sitecore XM Cloud", "requestorName": "James Ganswindt", "requestorEmail": "jganswindt@smartling.com", "company": "Blue Yonder", "contact": "Jeff Edgett", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked, You would prefer that we do not ask (Strategic Customer)", "competitors": "Think TPT? Doesn't work well from what I hear", "workaround": "Smartling GDN", "context": "Not an urgent ask, but Blue Yonder is using the GDN and interested in other options in the future", "submittedAt": "2025-04-03T09:20:18Z", "source": "historical"},
  {"id": 66, "date": "2025-04-03", "integration": "Sitecore XM Cloud", "requestorName": "Lynn Nguyen", "requestorEmail": "lnguyen@smartling.com", "company": "Ascension", "contact": "Greg Ellis", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000DVQA1YAP/view", "urgency": "Must Have requirement for an RFP/RFI", "funding": "No", "competitors": "Transperfect", "workaround": "", "context": "Ascension will be migrating to Sitecore XM Cloud next year", "submittedAt": "2025-04-03T09:34:01Z", "source": "historical"},
  {"id": 67, "date": "2025-04-10", "integration": "Coremedia", "requestorName": "David McNeil", "requestorEmail": "dmcneil@smartling.com", "company": "T-Systems", "contact": "sven.petzoldt@telekom.de", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000Fd9dwYAB/view", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "It was not asked", "competitors": "Global Link", "workaround": "", "context": "", "submittedAt": "2025-04-10T02:31:54Z", "source": "historical"},
  {"id": 68, "date": "2025-04-14", "integration": "Zeta Global", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Epic Games", "contact": "", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "N/A", "workaround": "Smartling API", "context": "Very early - sounds more like a nice to have. We have shared our API docs and suggested that approach first.", "submittedAt": "2025-04-14T06:39:12Z", "source": "historical"},
  {"id": 69, "date": "2025-05-11", "integration": "Salesforce Experience Cloud", "requestorName": "Kelly Stretz", "requestorEmail": "kstretz@smartling.com", "company": "FedEx", "contact": "Ash Cornelius", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "Yes", "competitors": "N/A", "workaround": "", "context": "FedEx is currently in RFP and will decide in the next two weeks. Account value is $521k/year. We originally committed to building them a SharePoint integration at no cost, but they are now saying Salesforce Experience Cloud is a higher priority.", "submittedAt": "2025-05-11T19:09:11Z", "source": "historical"},
  {"id": 70, "date": "2025-05-11", "integration": "Sonix", "requestorName": "Kelly Stretz", "requestorEmail": "kstretz@smartling.com", "company": "Cloudflare", "contact": "Alex Diaz-Garcia", "sfLink": "", "urgency": "No SLS opportunity upside, and provides Smartling customer retention and automation value", "funding": "Yes", "competitors": "No", "workaround": "", "context": "They would like to know how much it would cost to pay us to build this.", "submittedAt": "2025-05-11T19:10:29Z", "source": "historical"},
  {"id": 71, "date": "2025-05-15", "integration": "WhatsApp and Facebook messaging within Service Cloud", "requestorName": "Kian Graham", "requestorEmail": "kgraham@smartling.com", "company": "Vivino", "contact": "katy.petersen@vivino.com", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/001F0000013uAUhIAM/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "https://www.fluentic.com/", "workaround": "Not yet", "context": "Vivino won't fund it. Their new CPO just tried to rip out Smartling. WhatsApp and Facebook are getting used more and more.", "submittedAt": "2025-05-15T08:28:52Z", "source": "historical"},
  {"id": 72, "date": "2025-06-09", "integration": "Goldcast", "requestorName": "Kelly Stretz", "requestorEmail": "kstretz@smartling.com", "company": "Cloudflare", "contact": "David Fidalgo", "sfLink": "", "urgency": "No SLS opportunity upside, and provides Smartling customer retention and automation value", "funding": "Yes", "competitors": "Not that I can see", "workaround": "", "context": "Forwarding an email to Mike for reference about their use case - does not seem there is any ability to export.", "submittedAt": "2025-06-09T12:24:52Z", "source": "historical"},
  {"id": 73, "date": "2025-06-11", "integration": "TYPO3", "requestorName": "Michael Keller", "requestorEmail": "mkeller@smartling.com", "company": "Spectrum Brands", "contact": "", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "", "competitors": "Phrase, Wordbee, LanguageWire, Apostroph", "workaround": "", "context": "", "submittedAt": "2025-06-11T02:30:23Z", "source": "historical"},
  {"id": 74, "date": "2025-06-20", "integration": "Pardot - Marketing Cloud Account Engagement", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Zoom", "contact": "Stephanie Howell", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "N/A", "workaround": "", "context": "", "submittedAt": "2025-06-24T06:09:43Z", "source": "historical"},
  {"id": 75, "date": "2025-07-03", "integration": "Strapi", "requestorName": "Michael Keller", "requestorEmail": "mkeller@smartling.com", "company": "Adjust", "contact": "Tomoko Goto", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "Localazy, Crowdin", "workaround": "", "context": "", "submittedAt": "2025-07-03T01:43:18Z", "source": "historical"},
  {"id": 76, "date": "2025-07-03", "integration": "Sprinklr", "requestorName": "Michael Keller", "requestorEmail": "mkeller@smartling.com", "company": "T-Systems", "contact": "Maren Braitmaier", "sfLink": "", "urgency": "Initial interest from a QBR or inbound lead call. Opportunity is not yet qualified.", "funding": "It was not asked", "competitors": "Don't know", "workaround": "", "context": "", "submittedAt": "2025-07-03T01:48:40Z", "source": "historical"},
  {"id": 77, "date": "2025-07-15", "integration": "SAP Commerce Cloud", "requestorName": "David McNeil", "requestorEmail": "dmcneil@smartling.com", "company": "Henkel", "contact": "", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "It was not asked", "competitors": "Not sure", "workaround": "", "context": "", "submittedAt": "2025-07-15T09:12:06Z", "source": "historical"},
  {"id": 78, "date": "2025-09-09", "integration": "Sitecore Content Hub", "requestorName": "Max Stewart", "requestorEmail": "mstewart@smartling.com", "company": "Ascension Health", "contact": "Greg Ellis", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j000034t2Z0AAI/view", "urgency": "A new interested ISV Technology Partner integration request", "funding": "No", "competitors": "Not aware of any", "workaround": "", "context": "The Sitecore partnership team recently reached out to us about a Sitecore Content Hub integration. Request originated from Ascension Health.", "submittedAt": "2025-09-09T14:15:02Z", "source": "historical"},
  {"id": 79, "date": "2025-11-05", "integration": "Stibo PPL", "requestorName": "Mihaly Medzihradszky", "requestorEmail": "mmedzihradszky@smartling.com", "company": "Philips", "contact": "", "sfLink": "", "urgency": "Must Have requirement for an RFP/RFI", "funding": "Possibly", "competitors": "Across, RWS, Lionbridge, Transperfect", "workaround": "", "context": "", "submittedAt": "2025-11-05T07:12:05Z", "source": "historical"},
  {"id": 80, "date": "2025-11-03", "integration": "Gitbook", "requestorName": "Philippe St. Marseille", "requestorEmail": "pmarseille@smartling.com", "company": "Keeper Security", "contact": "Josh Klapow", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Possibly", "competitors": "Gitbook built-in MT", "workaround": "", "context": "Really important tool they use that is a strongly desired connector and would lead to more SLS income. Gitbook offers their own auto MT solution but according to Keeper, it's really bad and they want to use us.", "submittedAt": "2025-11-07T08:19:34Z", "source": "historical"},
  {"id": 81, "date": "2025-11-10", "integration": "Frontify", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Octave/Hexagon", "contact": "Stephen Columbus", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "N/A", "workaround": "Smartling API, exploratory phase right now", "context": "", "submittedAt": "2025-11-10T09:16:01Z", "source": "historical"},
  {"id": 82, "date": "2025-11-18", "integration": "Paligo CCMS", "requestorName": "Axel Billqvist", "requestorEmail": "abillqvist@smartling.com", "company": "HIAB / Cargotec", "contact": "Malin Tornblom / Elisa Repetti", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j00002ycAPXAA2/view", "urgency": "Must Have requirement for an RFP/RFI", "funding": "It was not asked, You would prefer that we do not ask (Strategic Customer)", "competitors": "Phrase, Crowdin, Transperfect, LanguageWire", "workaround": "", "context": "", "submittedAt": "2025-11-18T08:15:52Z", "source": "historical"},
  {"id": 83, "date": "2025-11-19", "integration": "PIMCORE PIM", "requestorName": "Michael Keller", "requestorEmail": "mkeller@smartling.com", "company": "Zumtobel", "contact": "", "sfLink": "https://smartling.lightning.force.com/lightning/r/Account/0013j00002cUPEmAAO/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "GlobalLink by TransPerfect, DeepL", "workaround": "", "context": "", "submittedAt": "2025-11-19T08:52:13Z", "source": "historical"},
  {"id": 84, "date": "2025-11-24", "integration": "Veeva", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "Hills Pet Nutrition", "contact": "Susan Wernimont PhD - Director, Innovation Acceleration", "sfLink": "", "urgency": "Nice to Have requirement for an RFP/RFI", "funding": "Possibly", "competitors": "Transperfect", "workaround": "Smartling API", "context": "", "submittedAt": "2025-11-24T12:57:38Z", "source": "historical"},
  {"id": 85, "date": "2026-03-05", "integration": "Frame.io", "requestorName": "Adam Noonan", "requestorEmail": "anoonan@smartling.com", "company": "IBM", "contact": "Denisa Despa", "sfLink": "No opp yet. IBM account", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "It was not asked", "competitors": "No", "workaround": "Either manual or through their WF integration (which is manual on their side)", "context": "Funding could be discussed with them particularly as we have no other requests for this", "submittedAt": "2026-03-05T09:56:34Z", "source": "historical"},
  {"id": 86, "date": "2026-03-16", "integration": "Adobe Journey Optimizer", "requestorName": "Dylan Rooney", "requestorEmail": "drooney@smartling.com", "company": "PMI", "contact": "Wolf Jean-Pierre", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000RyxVWYAZ/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "Transperfect", "workaround": "Smartling API", "context": "New logo and expansion on primary use case", "submittedAt": "2026-03-16T08:59:36Z", "source": "historical"},
  {"id": 87, "date": "2026-03-20", "integration": "Klaviyo", "requestorName": "Dave Jukich", "requestorEmail": "djukich@smartling.com", "company": "Vuori", "contact": "Greg Anderson, Director International Ecommerce", "sfLink": "https://smartling.lightning.force.com/lightning/r/Opportunity/006VK00000RIXafYAH/view", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "Possibly", "competitors": "TransPerfect (TP has a Klaviyo integration)", "workaround": "Klaviyo CSV export to Smartling was noted", "context": "Vuori has interest in Klaviyo integration to continue enterprise-wide use of Smartling. Greg also mentioned interest in Kustomer.io and reviews.io.", "submittedAt": "2026-03-20T11:11:06Z", "source": "historical"},
  {"id": 88, "date": "2026-04-06", "integration": "Zendesk Live Messaging", "requestorName": "Kelly Stretz", "requestorEmail": "kstretz@smartling.com", "company": "GoFundMe", "contact": "Kelly Leary", "sfLink": "", "urgency": "Existing Smartling customer and/or potential SLS opportunity upside", "funding": "No", "competitors": "I'm not sure", "workaround": "", "context": "", "submittedAt": "2026-04-06T07:44:17Z", "source": "historical"},
];
